### ISSUE TITLE
Parsenear corrdinate and allow for more {placeholders}

### ISSUE THREAD

**Issue by ElTodoFull** [DeathRealms/Expansion-ParseNear#1]
A parsenear a coordinate would also be very useful at least for my needs.
%parsenear_world_x_y_z_placeholder%
And also, allow more placeholders with {}
For example
%parsenear_hub_100_{obective_score_height}_100_{player}%

I'd be super thankful

**Comment by DeathRealms** [comment]
With the {} placeholders, are you referring to MVdW Placeholders?
